add-ShoppingCart-model-firstCommit
OlegShvets1/Book-Store pull request #11
Opened 2024-02-03 16:13 UTC by OlegShvets1

2024-02-03 17:30 UTC, olekskov requested changes

2024-02-03 17:30 UTC, olekskov commented on src/main/java/mate/academy/bookstore/service/impl/ShoppingCartServiceImpl.java
> +                        + user.getId() + "Add items to the shopping cart to initialize it."));
I don't like idea when shopping cart can be absent when user exists.
Please create shopping cart for user during registration.
Service should assume that cart already exists if user is and handle it's absense only in minimum amount that may be connected to some technical problems with DB and like that

2024-02-03 17:30 UTC, olekskov commented on src/main/java/mate/academy/bookstore/service/impl/ShoppingCartServiceImpl.java
> +    }
this logic -> during registration

2024-02-05 18:57 UTC, olekskov requested changes

2024-02-05 18:57 UTC, olekskov commented on src/main/java/mate/academy/bookstore/service/impl/UserServiceImpl.java
>      public UserResponseDto register(UserRegistrationRequestDto requestDto) {
We have 2 operations in method that modify DB state, better to use relevant annotation
```suggestion
    @Transactional
    public UserResponseDto register(UserRegistrationRequestDto requestDto) {
```

2024-02-05 18:57 UTC, olekskov commented on src/main/java/mate/academy/bookstore/service/impl/ShoppingCartServiceImpl.java
> +                });
I still don't like idea where we put something in DB during GET operation flow
```suggestion
        ShoppingCart shoppingCart = shoppingCartRepository.findByUserId(user.getId())
                .orElseThrow(() -> new IllegalStateException("Cart cannot be found for..."));
```

2024-02-05 18:57 UTC, olekskov commented on src/main/java/mate/academy/bookstore/service/impl/ShoppingCartServiceImpl.java
> +                .orElseGet(() -> createNewShoppingCart(user));
```suggestion
                .orElseThrow(() -> new IllegalStateException("Cart cannot be found for..."));
```

2024-02-05 18:57 UTC, olekskov commented on src/main/java/mate/academy/bookstore/service/impl/ShoppingCartServiceImpl.java
> +    }
```suggestion
```

2024-02-07 10:17 UTC, kozhukhovsky approved these changes

2024-02-07 16:19 UTC, merged