added_Order_model-firstCommit
OlegShvets1/Book-Store pull request #12
Opened 2024-02-08 18:21 UTC by OlegShvets1

2024-02-09 11:09 UTC, Vasul-Pankiv requested changes

2024-02-09 11:09 UTC, Vasul-Pankiv commented on src/main/java/mate/academy/bookstore/service/OrderService.java
> +    OrderResponseDto createOrder(Authentication authentication, Pageable pageable,
better to pass just userId here not Authentication (same with other methods)

2024-02-09 11:09 UTC, Vasul-Pankiv commented on src/main/java/mate/academy/bookstore/service/impl/OrderServiceImpl.java
> +        }
I think better just return empty list, it is general behavior for getAll() methods

2024-02-09 11:09 UTC, Vasul-Pankiv commented on src/main/java/mate/academy/bookstore/service/impl/OrderServiceImpl.java
> +    }
bad naming, you are not fulfilling, but just creating order items.

2024-02-09 11:09 UTC, Vasul-Pankiv commented on src/main/java/mate/academy/bookstore/service/impl/OrderServiceImpl.java
> +    private Order getValidOrder(Authentication authentication, Long orderId) {
Bad naming. The name should represent what the method does. But what is a valid Order?

2024-02-09 11:09 UTC, Vasul-Pankiv commented on src/main/java/mate/academy/bookstore/service/impl/OrderServiceImpl.java
> +    @Transactional
why it is transactional, it is just get

2024-02-09 11:09 UTC, Vasul-Pankiv commented on src/main/java/mate/academy/bookstore/service/impl/OrderServiceImpl.java
> +    @Override
Update method has to be transactional

2024-02-09 11:09 UTC, Vasul-Pankiv commented on src/main/resources/db/changelog/changes/09-create-orders-table.yaml
> +                    nullable: false
add empty line to the end of file

2024-02-09 11:09 UTC, Vasul-Pankiv commented on src/main/resources/db/changelog/changes/10-create-order-items-table.yaml
> +                  defaultValueBoolean: false
add empty line to the end of file

2024-02-09 11:09 UTC, Vasul-Pankiv commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: db/changelog/changes/10-create-order-items-table.yaml
add empty line to the end of file

2024-02-10 16:22 UTC, olekskov approved these changes

2024-02-10 17:50 UTC, merged