added_Ñsolution_Docker
OlegShvets1/Book-Store pull request #13
Opened 2024-02-11 08:37 UTC by OlegShvets1

- added DockerFile, docker-compose.yml, .env
- modified application.properties, liquibase.properties, pom.xml

2024-02-11 18:53 UTC, okuzan requested changes

2024-02-11 18:53 UTC, okuzan commented on .env
> +DEBUG_PORT=5005
the point of .env file is that it shouldn't be committed - it contains secrets. Not in your case, but that's a good practice to learn.

2024-02-11 18:53 UTC, okuzan commented on Dockerfile
> +EXPOSE 8080
don't forget that each file should end with exactly one empty line

2024-02-11 18:53 UTC, okuzan commented on docker-compose.yml
> +      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
```suggestion
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
      
```

2024-02-11 18:53 UTC, okuzan commented on docker-compose.yml
> +          "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect"
dialect is probably redundant

2024-02-12 18:39 UTC, olekskov requested changes

2024-02-12 18:39 UTC, olekskov commented on .env
env file is still in PR. Please remove it and add to .gitignore

2024-02-14 11:31 UTC, Vasul-Pankiv approved these changes

2024-02-19 17:53 UTC, merged