added_test_for_ShoppingCart1
OlegShvets1/Book-Store pull request #15
Opened 2024-02-29 19:24 UTC by OlegShvets1

2024-03-03 08:29 UTC, OlegShvets1 commented
![Screenshot_1](https://github.com/OlegShvets1/Book-Store/assets/109902490/e4b14762-c30f-4135-b0f6-288cd2b4c49c)
![Screenshot_2](https://github.com/OlegShvets1/Book-Store/assets/109902490/445500c9-873f-4651-8d85-0f132f85864e)

2024-03-04 11:09 UTC, okuzan requested changes
Review your sql scripts annotation, remove redundancy, if scripts are always used together - merge them, if it should be applied to each method of the class - extract it to a test level

2024-03-04 11:09 UTC, okuzan commented on src/test/resources/database/books/delete-user-from-db.sql
> +DELETE FROM users;
add an empty line to every script, where you see this symbol
![image](https://github.com/OlegShvets1/Book-Store/assets/49767049/b1ef905f-93b2-4669-b899-8f6fa5c77275)

2024-03-04 11:09 UTC, okuzan commented on src/test/java/mate/academy/bookstore/service/ShoppingCartServiceTest.java
> +        verify(cartItemRepository).findById(cartItemId);
why no assert of calling the delete method?

2024-03-04 11:09 UTC, okuzan commented on src/test/java/mate/academy/bookstore/controller/ShoppingCartControllerTest.java
> +            executionPhase = Sql.ExecutionPhase.BEFORE_TEST_METHOD)
extract to class level, you have it on each method

2024-03-04 11:09 UTC, okuzan commented on src/test/java/mate/academy/bookstore/controller/ShoppingCartControllerTest.java
> +            executionPhase = Sql.ExecutionPhase.AFTER_TEST_METHOD)
same

2024-03-05 09:57 UTC, okuzan approved these changes

2024-03-05 20:21 UTC, merged